/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
)

// checks if the PropertyListString type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PropertyListString{}

// PropertyListString struct for PropertyListString
type PropertyListString struct {
	Expression           *string  `json:"expression,omitempty"`
	Value                []string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PropertyListString PropertyListString

// NewPropertyListString instantiates a new PropertyListString object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPropertyListString() *PropertyListString {
	this := PropertyListString{}
	return &this
}

// NewPropertyListStringWithDefaults instantiates a new PropertyListString object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPropertyListStringWithDefaults() *PropertyListString {
	this := PropertyListString{}
	return &this
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *PropertyListString) GetExpression() string {
	if o == nil || IsNil(o.Expression) {
		var ret string
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertyListString) GetExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *PropertyListString) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given string and assigns it to the Expression field.
func (o *PropertyListString) SetExpression(v string) {
	o.Expression = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *PropertyListString) GetValue() []string {
	if o == nil || IsNil(o.Value) {
		var ret []string
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertyListString) GetValueOk() ([]string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *PropertyListString) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []string and assigns it to the Value field.
func (o *PropertyListString) SetValue(v []string) {
	o.Value = v
}

func (o PropertyListString) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PropertyListString) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PropertyListString) UnmarshalJSON(data []byte) (err error) {
	varPropertyListString := _PropertyListString{}

	err = json.Unmarshal(data, &varPropertyListString)

	if err != nil {
		return err
	}

	*o = PropertyListString(varPropertyListString)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "expression")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePropertyListString struct {
	value *PropertyListString
	isSet bool
}

func (v NullablePropertyListString) Get() *PropertyListString {
	return v.value
}

func (v *NullablePropertyListString) Set(val *PropertyListString) {
	v.value = val
	v.isSet = true
}

func (v NullablePropertyListString) IsSet() bool {
	return v.isSet
}

func (v *NullablePropertyListString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePropertyListString(val *PropertyListString) *NullablePropertyListString {
	return &NullablePropertyListString{value: val, isSet: true}
}

func (v NullablePropertyListString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePropertyListString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
