/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
)

// checks if the MeControllerApiUserDetailsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeControllerApiUserDetailsRequest{}

// MeControllerApiUserDetailsRequest struct for MeControllerApiUserDetailsRequest
type MeControllerApiUserDetailsRequest struct {
	FirstName            *string `json:"firstName,omitempty"`
	LastName             *string `json:"lastName,omitempty"`
	Email                *string `json:"email,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MeControllerApiUserDetailsRequest MeControllerApiUserDetailsRequest

// NewMeControllerApiUserDetailsRequest instantiates a new MeControllerApiUserDetailsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeControllerApiUserDetailsRequest() *MeControllerApiUserDetailsRequest {
	this := MeControllerApiUserDetailsRequest{}
	return &this
}

// NewMeControllerApiUserDetailsRequestWithDefaults instantiates a new MeControllerApiUserDetailsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeControllerApiUserDetailsRequestWithDefaults() *MeControllerApiUserDetailsRequest {
	this := MeControllerApiUserDetailsRequest{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *MeControllerApiUserDetailsRequest) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeControllerApiUserDetailsRequest) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *MeControllerApiUserDetailsRequest) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *MeControllerApiUserDetailsRequest) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *MeControllerApiUserDetailsRequest) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeControllerApiUserDetailsRequest) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *MeControllerApiUserDetailsRequest) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *MeControllerApiUserDetailsRequest) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *MeControllerApiUserDetailsRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeControllerApiUserDetailsRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *MeControllerApiUserDetailsRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *MeControllerApiUserDetailsRequest) SetEmail(v string) {
	o.Email = &v
}

func (o MeControllerApiUserDetailsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeControllerApiUserDetailsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MeControllerApiUserDetailsRequest) UnmarshalJSON(data []byte) (err error) {
	varMeControllerApiUserDetailsRequest := _MeControllerApiUserDetailsRequest{}

	err = json.Unmarshal(data, &varMeControllerApiUserDetailsRequest)

	if err != nil {
		return err
	}

	*o = MeControllerApiUserDetailsRequest(varMeControllerApiUserDetailsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "email")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMeControllerApiUserDetailsRequest struct {
	value *MeControllerApiUserDetailsRequest
	isSet bool
}

func (v NullableMeControllerApiUserDetailsRequest) Get() *MeControllerApiUserDetailsRequest {
	return v.value
}

func (v *NullableMeControllerApiUserDetailsRequest) Set(val *MeControllerApiUserDetailsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMeControllerApiUserDetailsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMeControllerApiUserDetailsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeControllerApiUserDetailsRequest(val *MeControllerApiUserDetailsRequest) *NullableMeControllerApiUserDetailsRequest {
	return &NullableMeControllerApiUserDetailsRequest{value: val, isSet: true}
}

func (v NullableMeControllerApiUserDetailsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeControllerApiUserDetailsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
