/*
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BlueprintWithFlow
 */
@JsonPropertyOrder({
  BlueprintWithFlow.JSON_PROPERTY_ID,
  BlueprintWithFlow.JSON_PROPERTY_TITLE,
  BlueprintWithFlow.JSON_PROPERTY_DESCRIPTION,
  BlueprintWithFlow.JSON_PROPERTY_TAGS,
  BlueprintWithFlow.JSON_PROPERTY_INCLUDED_TASKS,
  BlueprintWithFlow.JSON_PROPERTY_PUBLISHED_AT,
  BlueprintWithFlow.JSON_PROPERTY_DELETED,
  BlueprintWithFlow.JSON_PROPERTY_FLOW
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0-SNAPSHOT")
public class BlueprintWithFlow {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nonnull
  private String title;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_INCLUDED_TASKS = "includedTasks";
  @javax.annotation.Nullable
  private List<String> includedTasks = new ArrayList<>();

  public static final String JSON_PROPERTY_PUBLISHED_AT = "publishedAt";
  @javax.annotation.Nullable
  private OffsetDateTime publishedAt;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  @javax.annotation.Nonnull
  private Boolean deleted;

  public static final String JSON_PROPERTY_FLOW = "flow";
  @javax.annotation.Nonnull
  private String flow;

  public BlueprintWithFlow() {
  }

  public BlueprintWithFlow id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public BlueprintWithFlow title(@javax.annotation.Nonnull String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTitle(@javax.annotation.Nonnull String title) {
    this.title = title;
  }

  public BlueprintWithFlow description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public BlueprintWithFlow tags(@javax.annotation.Nullable List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public BlueprintWithFlow addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }

  public BlueprintWithFlow includedTasks(@javax.annotation.Nullable List<String> includedTasks) {
    
    this.includedTasks = includedTasks;
    return this;
  }

  public BlueprintWithFlow addIncludedTasksItem(String includedTasksItem) {
    if (this.includedTasks == null) {
      this.includedTasks = new ArrayList<>();
    }
    this.includedTasks.add(includedTasksItem);
    return this;
  }

  /**
   * Get includedTasks
   * @return includedTasks
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INCLUDED_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getIncludedTasks() {
    return includedTasks;
  }


  @JsonProperty(JSON_PROPERTY_INCLUDED_TASKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludedTasks(@javax.annotation.Nullable List<String> includedTasks) {
    this.includedTasks = includedTasks;
  }

  public BlueprintWithFlow publishedAt(@javax.annotation.Nullable OffsetDateTime publishedAt) {
    
    this.publishedAt = publishedAt;
    return this;
  }

  /**
   * Get publishedAt
   * @return publishedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPublishedAt() {
    return publishedAt;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishedAt(@javax.annotation.Nullable OffsetDateTime publishedAt) {
    this.publishedAt = publishedAt;
  }

  public BlueprintWithFlow deleted(@javax.annotation.Nonnull Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

  /**
   * Get deleted
   * @return deleted
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeleted(@javax.annotation.Nonnull Boolean deleted) {
    this.deleted = deleted;
  }

  public BlueprintWithFlow flow(@javax.annotation.Nonnull String flow) {
    
    this.flow = flow;
    return this;
  }

  /**
   * Get flow
   * @return flow
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLOW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFlow() {
    return flow;
  }


  @JsonProperty(JSON_PROPERTY_FLOW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlow(@javax.annotation.Nonnull String flow) {
    this.flow = flow;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlueprintWithFlow blueprintWithFlow = (BlueprintWithFlow) o;
    return Objects.equals(this.id, blueprintWithFlow.id) &&
        Objects.equals(this.title, blueprintWithFlow.title) &&
        Objects.equals(this.description, blueprintWithFlow.description) &&
        Objects.equals(this.tags, blueprintWithFlow.tags) &&
        Objects.equals(this.includedTasks, blueprintWithFlow.includedTasks) &&
        Objects.equals(this.publishedAt, blueprintWithFlow.publishedAt) &&
        Objects.equals(this.deleted, blueprintWithFlow.deleted) &&
        Objects.equals(this.flow, blueprintWithFlow.flow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, description, tags, includedTasks, publishedAt, deleted, flow);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlueprintWithFlow {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    includedTasks: ").append(toIndentedString(includedTasks)).append("\n");
    sb.append("    publishedAt: ").append(toIndentedString(publishedAt)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    flow: ").append(toIndentedString(flow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

