/*
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.sdk.model.Flow;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SearchResultFlow
 */
@JsonPropertyOrder({
  SearchResultFlow.JSON_PROPERTY_MODEL,
  SearchResultFlow.JSON_PROPERTY_FRAGMENTS
})
@JsonTypeName("SearchResult_Flow_")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0-SNAPSHOT")
public class SearchResultFlow {
  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nonnull
  private Flow model;

  public static final String JSON_PROPERTY_FRAGMENTS = "fragments";
  @javax.annotation.Nonnull
  private List<String> fragments = new ArrayList<>();

  public SearchResultFlow() {
  }

  public SearchResultFlow model(@javax.annotation.Nonnull Flow model) {
    
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Flow getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@javax.annotation.Nonnull Flow model) {
    this.model = model;
  }

  public SearchResultFlow fragments(@javax.annotation.Nonnull List<String> fragments) {
    
    this.fragments = fragments;
    return this;
  }

  public SearchResultFlow addFragmentsItem(String fragmentsItem) {
    if (this.fragments == null) {
      this.fragments = new ArrayList<>();
    }
    this.fragments.add(fragmentsItem);
    return this;
  }

  /**
   * Get fragments
   * @return fragments
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FRAGMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getFragments() {
    return fragments;
  }


  @JsonProperty(JSON_PROPERTY_FRAGMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFragments(@javax.annotation.Nonnull List<String> fragments) {
    this.fragments = fragments;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResultFlow searchResultFlow = (SearchResultFlow) o;
    return Objects.equals(this.model, searchResultFlow.model) &&
        Objects.equals(this.fragments, searchResultFlow.fragments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, fragments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResultFlow {\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    fragments: ").append(toIndentedString(fragments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

