/*
 * Kestra EE
 * All API operations allow an optional tenant identifier in the HTTP path, if you don't use multi-tenancy you must omit the tenant identifier.<br/> This means that, for example, when trying to access the Flows API, instead of using <code>/api/v1/{tenant}/flows</code> you must use <code>/api/v1/flows</code>.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.api.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.api.sdk.model.ExecutionMetadata;
import io.kestra.api.sdk.model.ExecutionTrigger;
import io.kestra.api.sdk.model.Label;
import io.kestra.api.sdk.model.State;
import io.kestra.api.sdk.model.TaskRun;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Execution
 */
@JsonPropertyOrder({
  Execution.JSON_PROPERTY_ID,
  Execution.JSON_PROPERTY_NAMESPACE,
  Execution.JSON_PROPERTY_FLOW_ID,
  Execution.JSON_PROPERTY_FLOW_REVISION,
  Execution.JSON_PROPERTY_TASK_RUN_LIST,
  Execution.JSON_PROPERTY_INPUTS,
  Execution.JSON_PROPERTY_OUTPUTS,
  Execution.JSON_PROPERTY_LABELS,
  Execution.JSON_PROPERTY_VARIABLES,
  Execution.JSON_PROPERTY_STATE,
  Execution.JSON_PROPERTY_PARENT_ID,
  Execution.JSON_PROPERTY_ORIGINAL_ID,
  Execution.JSON_PROPERTY_TRIGGER,
  Execution.JSON_PROPERTY_DELETED,
  Execution.JSON_PROPERTY_METADATA,
  Execution.JSON_PROPERTY_SCHEDULE_DATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-31T15:48:45.246126227Z[Etc/UTC]", comments = "Generator version: 7.11.0-SNAPSHOT")
public class Execution {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  @javax.annotation.Nonnull
  private String namespace;

  public static final String JSON_PROPERTY_FLOW_ID = "flowId";
  @javax.annotation.Nonnull
  private String flowId;

  public static final String JSON_PROPERTY_FLOW_REVISION = "flowRevision";
  @javax.annotation.Nonnull
  private Integer flowRevision;

  public static final String JSON_PROPERTY_TASK_RUN_LIST = "taskRunList";
  @javax.annotation.Nonnull
  private List<TaskRun> taskRunList = new ArrayList<>();

  public static final String JSON_PROPERTY_INPUTS = "inputs";
  @javax.annotation.Nonnull
  private Map<String, Object> inputs = new HashMap<>();

  public static final String JSON_PROPERTY_OUTPUTS = "outputs";
  @javax.annotation.Nonnull
  private Map<String, Object> outputs = new HashMap<>();

  public static final String JSON_PROPERTY_LABELS = "labels";
  @javax.annotation.Nonnull
  private List<Label> labels = new ArrayList<>();

  public static final String JSON_PROPERTY_VARIABLES = "variables";
  @javax.annotation.Nonnull
  private Map<String, Object> variables = new HashMap<>();

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nonnull
  private State state;

  public static final String JSON_PROPERTY_PARENT_ID = "parentId";
  @javax.annotation.Nonnull
  private String parentId;

  public static final String JSON_PROPERTY_ORIGINAL_ID = "originalId";
  @javax.annotation.Nonnull
  private String originalId;

  public static final String JSON_PROPERTY_TRIGGER = "trigger";
  @javax.annotation.Nonnull
  private ExecutionTrigger trigger;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  @javax.annotation.Nonnull
  private Boolean deleted;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nonnull
  private ExecutionMetadata metadata;

  public static final String JSON_PROPERTY_SCHEDULE_DATE = "scheduleDate";
  @javax.annotation.Nullable
  private OffsetDateTime scheduleDate;

  public Execution() {
  }

  public Execution id(@javax.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public Execution namespace(@javax.annotation.Nonnull String namespace) {
    
    this.namespace = namespace;
    return this;
  }

  /**
   * Get namespace
   * @return namespace
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNamespace() {
    return namespace;
  }


  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNamespace(@javax.annotation.Nonnull String namespace) {
    this.namespace = namespace;
  }

  public Execution flowId(@javax.annotation.Nonnull String flowId) {
    
    this.flowId = flowId;
    return this;
  }

  /**
   * Get flowId
   * @return flowId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLOW_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFlowId() {
    return flowId;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlowId(@javax.annotation.Nonnull String flowId) {
    this.flowId = flowId;
  }

  public Execution flowRevision(@javax.annotation.Nonnull Integer flowRevision) {
    
    this.flowRevision = flowRevision;
    return this;
  }

  /**
   * Get flowRevision
   * @return flowRevision
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLOW_REVISION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFlowRevision() {
    return flowRevision;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_REVISION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlowRevision(@javax.annotation.Nonnull Integer flowRevision) {
    this.flowRevision = flowRevision;
  }

  public Execution taskRunList(@javax.annotation.Nonnull List<TaskRun> taskRunList) {
    
    this.taskRunList = taskRunList;
    return this;
  }

  public Execution addTaskRunListItem(TaskRun taskRunListItem) {
    if (this.taskRunList == null) {
      this.taskRunList = new ArrayList<>();
    }
    this.taskRunList.add(taskRunListItem);
    return this;
  }

  /**
   * Get taskRunList
   * @return taskRunList
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TASK_RUN_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<TaskRun> getTaskRunList() {
    return taskRunList;
  }


  @JsonProperty(JSON_PROPERTY_TASK_RUN_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTaskRunList(@javax.annotation.Nonnull List<TaskRun> taskRunList) {
    this.taskRunList = taskRunList;
  }

  public Execution inputs(@javax.annotation.Nonnull Map<String, Object> inputs) {
    
    this.inputs = inputs;
    return this;
  }

  public Execution putInputsItem(String key, Object inputsItem) {
    this.inputs.put(key, inputsItem);
    return this;
  }

  /**
   * Get inputs
   * @return inputs
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INPUTS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)

  public Map<String, Object> getInputs() {
    return inputs;
  }


  @JsonProperty(JSON_PROPERTY_INPUTS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setInputs(@javax.annotation.Nonnull Map<String, Object> inputs) {
    this.inputs = inputs;
  }

  public Execution outputs(@javax.annotation.Nonnull Map<String, Object> outputs) {
    
    this.outputs = outputs;
    return this;
  }

  public Execution putOutputsItem(String key, Object outputsItem) {
    this.outputs.put(key, outputsItem);
    return this;
  }

  /**
   * Get outputs
   * @return outputs
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OUTPUTS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)

  public Map<String, Object> getOutputs() {
    return outputs;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUTS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setOutputs(@javax.annotation.Nonnull Map<String, Object> outputs) {
    this.outputs = outputs;
  }

  public Execution labels(@javax.annotation.Nonnull List<Label> labels) {
    
    this.labels = labels;
    return this;
  }

  public Execution addLabelsItem(Label labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Label> getLabels() {
    return labels;
  }


  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabels(@javax.annotation.Nonnull List<Label> labels) {
    this.labels = labels;
  }

  public Execution variables(@javax.annotation.Nonnull Map<String, Object> variables) {
    
    this.variables = variables;
    return this;
  }

  public Execution putVariablesItem(String key, Object variablesItem) {
    this.variables.put(key, variablesItem);
    return this;
  }

  /**
   * Get variables
   * @return variables
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VARIABLES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)

  public Map<String, Object> getVariables() {
    return variables;
  }


  @JsonProperty(JSON_PROPERTY_VARIABLES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setVariables(@javax.annotation.Nonnull Map<String, Object> variables) {
    this.variables = variables;
  }

  public Execution state(@javax.annotation.Nonnull State state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public State getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(@javax.annotation.Nonnull State state) {
    this.state = state;
  }

  public Execution parentId(@javax.annotation.Nonnull String parentId) {
    
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getParentId() {
    return parentId;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParentId(@javax.annotation.Nonnull String parentId) {
    this.parentId = parentId;
  }

  public Execution originalId(@javax.annotation.Nonnull String originalId) {
    
    this.originalId = originalId;
    return this;
  }

  /**
   * Get originalId
   * @return originalId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORIGINAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOriginalId() {
    return originalId;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginalId(@javax.annotation.Nonnull String originalId) {
    this.originalId = originalId;
  }

  public Execution trigger(@javax.annotation.Nonnull ExecutionTrigger trigger) {
    
    this.trigger = trigger;
    return this;
  }

  /**
   * Get trigger
   * @return trigger
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ExecutionTrigger getTrigger() {
    return trigger;
  }


  @JsonProperty(JSON_PROPERTY_TRIGGER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrigger(@javax.annotation.Nonnull ExecutionTrigger trigger) {
    this.trigger = trigger;
  }

  public Execution deleted(@javax.annotation.Nonnull Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

  /**
   * Get deleted
   * @return deleted
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeleted(@javax.annotation.Nonnull Boolean deleted) {
    this.deleted = deleted;
  }

  public Execution metadata(@javax.annotation.Nonnull ExecutionMetadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ExecutionMetadata getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetadata(@javax.annotation.Nonnull ExecutionMetadata metadata) {
    this.metadata = metadata;
  }

  public Execution scheduleDate(@javax.annotation.Nullable OffsetDateTime scheduleDate) {
    
    this.scheduleDate = scheduleDate;
    return this;
  }

  /**
   * Get scheduleDate
   * @return scheduleDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEDULE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getScheduleDate() {
    return scheduleDate;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScheduleDate(@javax.annotation.Nullable OffsetDateTime scheduleDate) {
    this.scheduleDate = scheduleDate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Execution execution = (Execution) o;
    return Objects.equals(this.id, execution.id) &&
        Objects.equals(this.namespace, execution.namespace) &&
        Objects.equals(this.flowId, execution.flowId) &&
        Objects.equals(this.flowRevision, execution.flowRevision) &&
        Objects.equals(this.taskRunList, execution.taskRunList) &&
        Objects.equals(this.inputs, execution.inputs) &&
        Objects.equals(this.outputs, execution.outputs) &&
        Objects.equals(this.labels, execution.labels) &&
        Objects.equals(this.variables, execution.variables) &&
        Objects.equals(this.state, execution.state) &&
        Objects.equals(this.parentId, execution.parentId) &&
        Objects.equals(this.originalId, execution.originalId) &&
        Objects.equals(this.trigger, execution.trigger) &&
        Objects.equals(this.deleted, execution.deleted) &&
        Objects.equals(this.metadata, execution.metadata) &&
        Objects.equals(this.scheduleDate, execution.scheduleDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, namespace, flowId, flowRevision, taskRunList, inputs, outputs, labels, variables, state, parentId, originalId, trigger, deleted, metadata, scheduleDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Execution {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    flowId: ").append(toIndentedString(flowId)).append("\n");
    sb.append("    flowRevision: ").append(toIndentedString(flowRevision)).append("\n");
    sb.append("    taskRunList: ").append(toIndentedString(taskRunList)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    originalId: ").append(toIndentedString(originalId)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    scheduleDate: ").append(toIndentedString(scheduleDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `namespace` to the URL query string
    if (getNamespace() != null) {
      try {
        joiner.add(String.format("%snamespace%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNamespace()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `flowId` to the URL query string
    if (getFlowId() != null) {
      try {
        joiner.add(String.format("%sflowId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFlowId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `flowRevision` to the URL query string
    if (getFlowRevision() != null) {
      try {
        joiner.add(String.format("%sflowRevision%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFlowRevision()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `taskRunList` to the URL query string
    if (getTaskRunList() != null) {
      for (int i = 0; i < getTaskRunList().size(); i++) {
        if (getTaskRunList().get(i) != null) {
          joiner.add(getTaskRunList().get(i).toUrlQueryString(String.format("%staskRunList%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `inputs` to the URL query string
    if (getInputs() != null) {
      for (String _key : getInputs().keySet()) {
        try {
          joiner.add(String.format("%sinputs%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
              getInputs().get(_key), URLEncoder.encode(String.valueOf(getInputs().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `outputs` to the URL query string
    if (getOutputs() != null) {
      for (String _key : getOutputs().keySet()) {
        try {
          joiner.add(String.format("%soutputs%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
              getOutputs().get(_key), URLEncoder.encode(String.valueOf(getOutputs().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `labels` to the URL query string
    if (getLabels() != null) {
      for (int i = 0; i < getLabels().size(); i++) {
        if (getLabels().get(i) != null) {
          joiner.add(getLabels().get(i).toUrlQueryString(String.format("%slabels%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `variables` to the URL query string
    if (getVariables() != null) {
      for (String _key : getVariables().keySet()) {
        try {
          joiner.add(String.format("%svariables%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
              getVariables().get(_key), URLEncoder.encode(String.valueOf(getVariables().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `state` to the URL query string
    if (getState() != null) {
      joiner.add(getState().toUrlQueryString(prefix + "state" + suffix));
    }

    // add `parentId` to the URL query string
    if (getParentId() != null) {
      try {
        joiner.add(String.format("%sparentId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getParentId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `originalId` to the URL query string
    if (getOriginalId() != null) {
      try {
        joiner.add(String.format("%soriginalId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getOriginalId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `trigger` to the URL query string
    if (getTrigger() != null) {
      joiner.add(getTrigger().toUrlQueryString(prefix + "trigger" + suffix));
    }

    // add `deleted` to the URL query string
    if (getDeleted() != null) {
      try {
        joiner.add(String.format("%sdeleted%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeleted()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(getMetadata().toUrlQueryString(prefix + "metadata" + suffix));
    }

    // add `scheduleDate` to the URL query string
    if (getScheduleDate() != null) {
      try {
        joiner.add(String.format("%sscheduleDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getScheduleDate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

