/*
 * Kestra EE
 * All API operations allow an optional tenant identifier in the HTTP path, if you don't use multi-tenancy you must omit the tenant identifier.<br/> This means that, for example, when trying to access the Flows API, instead of using <code>/api/v1/{tenant}/flows</code> you must use <code>/api/v1/flows</code>.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.api.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.api.sdk.model.Metric;
import io.kestra.api.sdk.model.ServerConfig;
import io.kestra.api.sdk.model.ServerInstance;
import io.kestra.api.sdk.model.ServiceInstanceTimestampedEvent;
import io.kestra.api.sdk.model.ServiceServiceState;
import io.kestra.api.sdk.model.ServiceType;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * ServiceInstance
 */
@JsonPropertyOrder({
  ServiceInstance.JSON_PROPERTY_SERVER,
  ServiceInstance.JSON_PROPERTY_METRICS,
  ServiceInstance.JSON_PROPERTY_STATE,
  ServiceInstance.JSON_PROPERTY_ID,
  ServiceInstance.JSON_PROPERTY_TYPE,
  ServiceInstance.JSON_PROPERTY_CREATED_AT,
  ServiceInstance.JSON_PROPERTY_UPDATED_AT,
  ServiceInstance.JSON_PROPERTY_EVENTS,
  ServiceInstance.JSON_PROPERTY_CONFIG,
  ServiceInstance.JSON_PROPERTY_PROPS,
  ServiceInstance.JSON_PROPERTY_SEQ_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-05T07:35:23.657005690Z[Etc/UTC]", comments = "Generator version: 7.14.0-SNAPSHOT")
public class ServiceInstance {
  public static final String JSON_PROPERTY_SERVER = "server";
  @javax.annotation.Nonnull
  private ServerInstance server;

  public static final String JSON_PROPERTY_METRICS = "metrics";
  @javax.annotation.Nonnull
  private List<Metric> metrics = new ArrayList<>();

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nonnull
  private ServiceServiceState state;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ServiceType type;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_EVENTS = "events";
  @javax.annotation.Nonnull
  private List<ServiceInstanceTimestampedEvent> events = new ArrayList<>();

  public static final String JSON_PROPERTY_CONFIG = "config";
  @javax.annotation.Nonnull
  private ServerConfig config;

  public static final String JSON_PROPERTY_PROPS = "props";
  @javax.annotation.Nonnull
  private Map<String, Object> props = new HashMap<>();

  public static final String JSON_PROPERTY_SEQ_ID = "seqId";
  @javax.annotation.Nonnull
  private Long seqId;

  public ServiceInstance() {
  }

  public ServiceInstance server(@javax.annotation.Nonnull ServerInstance server) {
    
    this.server = server;
    return this;
  }

  /**
   * Get server
   * @return server
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SERVER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ServerInstance getServer() {
    return server;
  }


  @JsonProperty(JSON_PROPERTY_SERVER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setServer(@javax.annotation.Nonnull ServerInstance server) {
    this.server = server;
  }

  public ServiceInstance metrics(@javax.annotation.Nonnull List<Metric> metrics) {
    
    this.metrics = metrics;
    return this;
  }

  public ServiceInstance addMetricsItem(Metric metricsItem) {
    if (this.metrics == null) {
      this.metrics = new ArrayList<>();
    }
    this.metrics.add(metricsItem);
    return this;
  }

  /**
   * Get metrics
   * @return metrics
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METRICS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Metric> getMetrics() {
    return metrics;
  }


  @JsonProperty(JSON_PROPERTY_METRICS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetrics(@javax.annotation.Nonnull List<Metric> metrics) {
    this.metrics = metrics;
  }

  public ServiceInstance state(@javax.annotation.Nonnull ServiceServiceState state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ServiceServiceState getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(@javax.annotation.Nonnull ServiceServiceState state) {
    this.state = state;
  }

  public ServiceInstance id(@javax.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public ServiceInstance type(@javax.annotation.Nonnull ServiceType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ServiceType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ServiceType type) {
    this.type = type;
  }

  public ServiceInstance createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ServiceInstance updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ServiceInstance events(@javax.annotation.Nonnull List<ServiceInstanceTimestampedEvent> events) {
    
    this.events = events;
    return this;
  }

  public ServiceInstance addEventsItem(ServiceInstanceTimestampedEvent eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Get events
   * @return events
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ServiceInstanceTimestampedEvent> getEvents() {
    return events;
  }


  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvents(@javax.annotation.Nonnull List<ServiceInstanceTimestampedEvent> events) {
    this.events = events;
  }

  public ServiceInstance config(@javax.annotation.Nonnull ServerConfig config) {
    
    this.config = config;
    return this;
  }

  /**
   * Get config
   * @return config
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ServerConfig getConfig() {
    return config;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfig(@javax.annotation.Nonnull ServerConfig config) {
    this.config = config;
  }

  public ServiceInstance props(@javax.annotation.Nonnull Map<String, Object> props) {
    
    this.props = props;
    return this;
  }

  public ServiceInstance putPropsItem(String key, Object propsItem) {
    this.props.put(key, propsItem);
    return this;
  }

  /**
   * Get props
   * @return props
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROPS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)

  public Map<String, Object> getProps() {
    return props;
  }


  @JsonProperty(JSON_PROPERTY_PROPS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setProps(@javax.annotation.Nonnull Map<String, Object> props) {
    this.props = props;
  }

  public ServiceInstance seqId(@javax.annotation.Nonnull Long seqId) {
    
    this.seqId = seqId;
    return this;
  }

  /**
   * Get seqId
   * @return seqId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEQ_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSeqId() {
    return seqId;
  }


  @JsonProperty(JSON_PROPERTY_SEQ_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeqId(@javax.annotation.Nonnull Long seqId) {
    this.seqId = seqId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceInstance serviceInstance = (ServiceInstance) o;
    return Objects.equals(this.server, serviceInstance.server) &&
        Objects.equals(this.metrics, serviceInstance.metrics) &&
        Objects.equals(this.state, serviceInstance.state) &&
        Objects.equals(this.id, serviceInstance.id) &&
        Objects.equals(this.type, serviceInstance.type) &&
        Objects.equals(this.createdAt, serviceInstance.createdAt) &&
        Objects.equals(this.updatedAt, serviceInstance.updatedAt) &&
        Objects.equals(this.events, serviceInstance.events) &&
        Objects.equals(this.config, serviceInstance.config) &&
        Objects.equals(this.props, serviceInstance.props) &&
        Objects.equals(this.seqId, serviceInstance.seqId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(server, metrics, state, id, type, createdAt, updatedAt, events, config, props, seqId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceInstance {\n");
    sb.append("    server: ").append(toIndentedString(server)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("    seqId: ").append(toIndentedString(seqId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `server` to the URL query string
    if (getServer() != null) {
      joiner.add(getServer().toUrlQueryString(prefix + "server" + suffix));
    }

    // add `metrics` to the URL query string
    if (getMetrics() != null) {
      for (int i = 0; i < getMetrics().size(); i++) {
        if (getMetrics().get(i) != null) {
          joiner.add(getMetrics().get(i).toUrlQueryString(String.format("%smetrics%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `state` to the URL query string
    if (getState() != null) {
      try {
        joiner.add(String.format("%sstate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getState()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      try {
        joiner.add(String.format("%screatedAt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      try {
        joiner.add(String.format("%supdatedAt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdatedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `events` to the URL query string
    if (getEvents() != null) {
      for (int i = 0; i < getEvents().size(); i++) {
        if (getEvents().get(i) != null) {
          joiner.add(getEvents().get(i).toUrlQueryString(String.format("%sevents%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `config` to the URL query string
    if (getConfig() != null) {
      joiner.add(getConfig().toUrlQueryString(prefix + "config" + suffix));
    }

    // add `props` to the URL query string
    if (getProps() != null) {
      for (String _key : getProps().keySet()) {
        try {
          joiner.add(String.format("%sprops%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
              getProps().get(_key), URLEncoder.encode(String.valueOf(getProps().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `seqId` to the URL query string
    if (getSeqId() != null) {
      try {
        joiner.add(String.format("%sseqId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSeqId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

