/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiSecretMeta from './ApiSecretMeta';
import ApiSecretTag from './ApiSecretTag';

/**
 * The ApiSecretMetaEE model module.
 * @module model/ApiSecretMetaEE
 * @version 1.0.0-beta5
 */
class ApiSecretMetaEE {
    /**
     * Constructs a new <code>ApiSecretMetaEE</code>.
     * @alias module:model/ApiSecretMetaEE
     * @implements module:model/ApiSecretMeta
     * @param key {String} 
     */
    constructor(key) { 
        ApiSecretMeta.initialize(this, key);
        ApiSecretMetaEE.initialize(this, key);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key) { 
        obj['description'] = description;
        obj['tags'] = tags;
        obj['key'] = key;
    }

    /**
     * Constructs a <code>ApiSecretMetaEE</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiSecretMetaEE} obj Optional instance to populate.
     * @return {module:model/ApiSecretMetaEE} The populated <code>ApiSecretMetaEE</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiSecretMetaEE();
            ApiSecretMeta.constructFromObject(data, obj);

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [ApiSecretTag]);
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiSecretMetaEE</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiSecretMetaEE</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ApiSecretMetaEE.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['tags']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tags'])) {
                throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
            }
            // validate the optional field `tags` (array)
            for (const item of data['tags']) {
                ApiSecretTag.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }

        return true;
    }


}

ApiSecretMetaEE.RequiredProperties = ["description", "tags", "key"];

/**
 * @member {String} description
 */
ApiSecretMetaEE.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/ApiSecretTag>} tags
 */
ApiSecretMetaEE.prototype['tags'] = undefined;

/**
 * @member {String} key
 */
ApiSecretMetaEE.prototype['key'] = undefined;


// Implement ApiSecretMeta interface:
/**
 * @member {String} key
 */
ApiSecretMeta.prototype['key'] = undefined;




export default ApiSecretMetaEE;

