/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AppsControllerApiAppTags model module.
 * @module model/AppsControllerApiAppTags
 * @version 1.0.0-beta5
 */
class AppsControllerApiAppTags {
    /**
     * Constructs a new <code>AppsControllerApiAppTags</code>.
     * @alias module:model/AppsControllerApiAppTags
     * @param tags {Array.<String>} 
     */
    constructor(tags) { 
        
        AppsControllerApiAppTags.initialize(this, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tags) { 
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>AppsControllerApiAppTags</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppsControllerApiAppTags} obj Optional instance to populate.
     * @return {module:model/AppsControllerApiAppTags} The populated <code>AppsControllerApiAppTags</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppsControllerApiAppTags();

            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppsControllerApiAppTags</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppsControllerApiAppTags</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AppsControllerApiAppTags.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}

AppsControllerApiAppTags.RequiredProperties = ["tags"];

/**
 * @member {Array.<String>} tags
 */
AppsControllerApiAppTags.prototype['tags'] = undefined;






export default AppsControllerApiAppTags;

