/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CrudEventType.
* @enum {}
* @readonly
*/
export default class CrudEventType {
    
        /**
         * value: "READ"
         * @const
         */
        "READ" = "READ";

    
        /**
         * value: "CREATE"
         * @const
         */
        "CREATE" = "CREATE";

    
        /**
         * value: "UPDATE"
         * @const
         */
        "UPDATE" = "UPDATE";

    
        /**
         * value: "DELETE"
         * @const
         */
        "DELETE" = "DELETE";

    
        /**
         * value: "LOGIN"
         * @const
         */
        "LOGIN" = "LOGIN";

    
        /**
         * value: "LOGOUT"
         * @const
         */
        "LOGOUT" = "LOGOUT";

    
        /**
         * value: "IMPERSONATE"
         * @const
         */
        "IMPERSONATE" = "IMPERSONATE";

    
        /**
         * value: "LOGIN_FAILURE"
         * @const
         */
        "LOGIN_FAILURE" = "LOGIN_FAILURE";

    
        /**
         * value: "ACCOUNT_LOCKED"
         * @const
         */
        "ACCOUNT_LOCKED" = "ACCOUNT_LOCKED";

    

    /**
    * Returns a <code>CrudEventType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CrudEventType} The enum <code>CrudEventType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

