/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MapObjectObject from './MapObjectObject';

/**
 * The FlowWithSourceAllOfLabels model module.
 * @module model/FlowWithSourceAllOfLabels
 * @version v0.24.0
 */
class FlowWithSourceAllOfLabels {
    /**
     * Constructs a new <code>FlowWithSourceAllOfLabels</code>.
     * @alias module:model/FlowWithSourceAllOfLabels
     * @param {(module:model/MapObjectObject|module:model/[String])} instance The actual instance to initialize FlowWithSourceAllOfLabels.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate array data type
            if (!Array.isArray(instance)) {
                throw new Error("Invalid data type. Expecting array. Input: " + instance);
            }
            // validate array of string
            for (const item of instance) {
                if (!(typeof item === 'number' && item % 1 === 0)) {
                    throw new Error("Invalid array items. Must be string. Input: " + instance);
                }
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into [String]
            errorMessages.push("Failed to construct [String]: " + err)
        }

        try {
            if (typeof instance === "MapObjectObject") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MapObjectObject.validateJSON(instance); // throw an exception if no match
                // create MapObjectObject from JS object
                this.actualInstance = MapObjectObject.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MapObjectObject
            errorMessages.push("Failed to construct MapObjectObject: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `FlowWithSourceAllOfLabels` with oneOf schemas MapObjectObject, [String]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `FlowWithSourceAllOfLabels` with oneOf schemas MapObjectObject, [String]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>FlowWithSourceAllOfLabels</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FlowWithSourceAllOfLabels} obj Optional instance to populate.
     * @return {module:model/FlowWithSourceAllOfLabels} The populated <code>FlowWithSourceAllOfLabels</code> instance.
     */
    static constructFromObject(data, obj) {
        return new FlowWithSourceAllOfLabels(data);
    }

    /**
     * Gets the actual instance, which can be <code>MapObjectObject</code>, <code>[String]</code>.
     * @return {(module:model/MapObjectObject|module:model/[String])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MapObjectObject</code>, <code>[String]</code>.
     * @param {(module:model/MapObjectObject|module:model/[String])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = FlowWithSourceAllOfLabels.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of FlowWithSourceAllOfLabels from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/FlowWithSourceAllOfLabels} An instance of FlowWithSourceAllOfLabels.
     */
    static fromJSON = function(json_string){
        return FlowWithSourceAllOfLabels.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {Boolean} empty
 */
FlowWithSourceAllOfLabels.prototype['empty'] = undefined;


FlowWithSourceAllOfLabels.OneOf = ["MapObjectObject", "[String]"];

export default FlowWithSourceAllOfLabels;

