/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IAMUserControllerApiTenant model module.
 * @module model/IAMUserControllerApiTenant
 * @version v0.24.0
 */
class IAMUserControllerApiTenant {
    /**
     * Constructs a new <code>IAMUserControllerApiTenant</code>.
     * @alias module:model/IAMUserControllerApiTenant
     */
    constructor() { 
        
        IAMUserControllerApiTenant.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IAMUserControllerApiTenant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IAMUserControllerApiTenant} obj Optional instance to populate.
     * @return {module:model/IAMUserControllerApiTenant} The populated <code>IAMUserControllerApiTenant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IAMUserControllerApiTenant();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IAMUserControllerApiTenant</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IAMUserControllerApiTenant</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
IAMUserControllerApiTenant.prototype['id'] = undefined;

/**
 * @member {String} name
 */
IAMUserControllerApiTenant.prototype['name'] = undefined;






export default IAMUserControllerApiTenant;

