/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstanceControllerApiActiveService from './InstanceControllerApiActiveService';

/**
 * The InstanceControllerApiActiveServiceList model module.
 * @module model/InstanceControllerApiActiveServiceList
 * @version 1.0.0
 */
class InstanceControllerApiActiveServiceList {
    /**
     * Constructs a new <code>InstanceControllerApiActiveServiceList</code>.
     * @alias module:model/InstanceControllerApiActiveServiceList
     * @param total {Number} 
     * @param services {Array.<module:model/InstanceControllerApiActiveService>} 
     */
    constructor(total, services) { 
        
        InstanceControllerApiActiveServiceList.initialize(this, total, services);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, total, services) { 
        obj['total'] = total;
        obj['services'] = services;
    }

    /**
     * Constructs a <code>InstanceControllerApiActiveServiceList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstanceControllerApiActiveServiceList} obj Optional instance to populate.
     * @return {module:model/InstanceControllerApiActiveServiceList} The populated <code>InstanceControllerApiActiveServiceList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstanceControllerApiActiveServiceList();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('services')) {
                obj['services'] = ApiClient.convertToType(data['services'], [InstanceControllerApiActiveService]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InstanceControllerApiActiveServiceList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InstanceControllerApiActiveServiceList</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InstanceControllerApiActiveServiceList.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['services']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['services'])) {
                throw new Error("Expected the field `services` to be an array in the JSON data but got " + data['services']);
            }
            // validate the optional field `services` (array)
            for (const item of data['services']) {
                InstanceControllerApiActiveService.validateJSON(item);
            };
        }

        return true;
    }


}

InstanceControllerApiActiveServiceList.RequiredProperties = ["total", "services"];

/**
 * @member {Number} total
 */
InstanceControllerApiActiveServiceList.prototype['total'] = undefined;

/**
 * @member {Array.<module:model/InstanceControllerApiActiveService>} services
 */
InstanceControllerApiActiveServiceList.prototype['services'] = undefined;






export default InstanceControllerApiActiveServiceList;

