/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MiscControllerEdition.
* @enum {}
* @readonly
*/
export default class MiscControllerEdition {
    
        /**
         * value: "OSS"
         * @const
         */
        "OSS" = "OSS";

    
        /**
         * value: "EE"
         * @const
         */
        "EE" = "EE";

    

    /**
    * Returns a <code>MiscControllerEdition</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MiscControllerEdition} The enum <code>MiscControllerEdition</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

