/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceProviderConfigurationSupportedConfiguration from './ServiceProviderConfigurationSupportedConfiguration';

/**
 * The ServiceProviderConfigurationFilterConfiguration model module.
 * @module model/ServiceProviderConfigurationFilterConfiguration
 * @version v0.24.0
 */
class ServiceProviderConfigurationFilterConfiguration {
    /**
     * Constructs a new <code>ServiceProviderConfigurationFilterConfiguration</code>.
     * @alias module:model/ServiceProviderConfigurationFilterConfiguration
     * @implements module:model/ServiceProviderConfigurationSupportedConfiguration
     */
    constructor() { 
        ServiceProviderConfigurationSupportedConfiguration.initialize(this);
        ServiceProviderConfigurationFilterConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceProviderConfigurationFilterConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceProviderConfigurationFilterConfiguration} obj Optional instance to populate.
     * @return {module:model/ServiceProviderConfigurationFilterConfiguration} The populated <code>ServiceProviderConfigurationFilterConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceProviderConfigurationFilterConfiguration();
            ServiceProviderConfigurationSupportedConfiguration.constructFromObject(data, obj);

            if (data.hasOwnProperty('supported')) {
                obj['supported'] = ApiClient.convertToType(data['supported'], 'Boolean');
            }
            if (data.hasOwnProperty('maxResults')) {
                obj['maxResults'] = ApiClient.convertToType(data['maxResults'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceProviderConfigurationFilterConfiguration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceProviderConfigurationFilterConfiguration</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} supported
 */
ServiceProviderConfigurationFilterConfiguration.prototype['supported'] = undefined;

/**
 * @member {Number} maxResults
 */
ServiceProviderConfigurationFilterConfiguration.prototype['maxResults'] = undefined;


// Implement ServiceProviderConfigurationSupportedConfiguration interface:
/**
 * @member {Boolean} supported
 */
ServiceProviderConfigurationSupportedConfiguration.prototype['supported'] = undefined;




export default ServiceProviderConfigurationFilterConfiguration;

